### ISSUE TITLE
"Failed to communicate with server"

### ISSUE THREAD

**Issue by iambrainlag** [mchugh19/zabbix-vue#74]
Dear dev,

thank you for your effort for creating & maintaining this extension!  After the last update to 3.0.0 we are unable to connect to our zabbix server. 

The error is: "Failed to communicate with server" and using versions 2.2.0 (on firefox) using the same settings we was able to connect and use the extension with no problem. 

Our zabbix server is version 4.2.8

Please let me know if you need any details or further information in order to short this matter out.

**Comment by dacrhu** [comment]
Same error:

Zabbix: 6.0.36
Zabbix Vue: 3.0.0

Logs:

Access to fetch at 'https://****/api_jsonrpc.php' from origin 'chrome-extension://****' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

Error communicating with: https://****

**Comment by mchugh19** [comment]
Sorry for that. This should be fixed in version 3.0.1 which was just uploaded. Seems there needed to be an explict CORS policy for some situations. 

If you continue to have issues, please reopen.

**Comment by iambrainlag** [comment]
Hello Christian and thank you for your kind support. 

I installed zabbix vue 3.0.1 on firefox 135.0.1 (64-bit) and still facing the same issue ("Failed to communicate with server") .

Best Regards,
Alex

**Comment by dacrhu** [comment]
Unfortunately, no updates can be found in the Chrome Webstore.

**Comment by digdug3** [comment]
@iambrainlag, @mchugh19 please Reopen this Issue
We use Firefox with version 3.0.3, when I start Firefox Zabbix Vua does not connect to the Zabbix server, I have to go to options and press "Save" to enable the monitoring again

**Comment by mchugh19** [comment]
> please Reopen this Issue. We use Firefox with version 3.0.3, when I start Firefox Zabbix Vua does not connect to the Zabbix server, I have to go to options and press "Save" to enable the monitoring again.

After the options have been saved, does the connection sometimes break and display the error again? Or does it it keep working once saved? Under what circumstancesdo you get the message?

**Comment by digdug3** [comment]
After saving it just works, but after restarting Firefox (multiple PC's) you have to press "Save" again to get it working.

**Comment by mchugh19** [comment]
This should be corrected in just released 3.0.4. This fixes an issue where the extension did not immedialy connect to Zabbix servers when the browser was restarted. Please re-open if you are still experiencing issues.

**Comment by digdug3** [comment]
Just updated to 3.0.4, restarted serveral times and your great extention is working again! Thank you for the quick fix!
