### ISSUE TITLE
Issue with Zabbix-Vue v3 and Zabbix Server 7.2

### ISSUE THREAD

**Issue by joseaanlo7** [mchugh19/zabbix-vue#75]
Hi!

Thank you for updating zabbix-vue to version 3! We really appreciate your work.

However, we are experiencing an issue when trying to connect to our Zabbix Server 7.2, which uses token authentication. The extension fails with the following message:

_"Check server configuration in extension options: No servers defined"_

Could you check if Zabbix-Vue v3 supports token authentication in Zabbix 7.2?

Thanks again for your efforts!

**Comment by mchugh19** [comment]
Sorry for that. This should be fixed in version 3.0.1 which was just uploaded. Seems there needed to be an explict CORS policy for some situations. 

If you continue to have issues, please reopen.

**Comment by joseaanlo7** [comment]
Hi!

Thanks for the quick update. I've just updated to version 3.0.1, but unfortunately, I'm still experiencing the same issue on my Zabbix Server 7.2.

I’ve also tried logging in with a username and password instead of a token, but it still doesn’t work. However, everything works fine on my old Zabbix Server 6.4.

Do you have any suggestions on how to resolve this?

Thanks again for your help!
